export const START_GET_GESTATION = "START_GET_GESTATION";
export const GET_GESTATION_SUCCESS = "GET_GESTATION_SUCCESS";
export const GET_GESTATION_FAILURE = "GET_GESTATION_FAILURE";
export const SET_GESTATION = "SET_GESTATION";
